version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: ./deployment/local/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../..:/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../../.envs/.postgres

  redis:
    image: redis:7-alpine
    restart: always

  # celery-worker:
  #   build:
  #     context: ../..
  #     dockerfile: ./deployment/local/Dockerfile
  #   depends_on:
  #     - db
  #     - redis
  #     - web
  #   command: celery -A therapy_connect worker -l info

  # celery-beat:
  #   build:
  #     context: ../..
  #     dockerfile: ./deployment/local/Dockerfile
  #   depends_on:
  #     - db
  #     - redis
  #     - web
  #   command: celery -A therapy_connect beat -l info

  celery-worker:
    build:
      context: ../..
      dockerfile: ./deployment/local/Dockerfile
    depends_on:
      - db
      - redis
      - web
    command: celery -A therapy_connect worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=therapy_connect.settings.local
    restart: always

  celery-beat:
    build:
      context: ../..
      dockerfile: ./deployment/local/Dockerfile
    depends_on:
      - db
      - redis
      - web
    command: celery -A therapy_connect beat -l info
    environment:
      - DJANGO_SETTINGS_MODULE=therapy_connect.settings.local
    restart: always


volumes:
  postgres_data: {}