# Generated by Django 5.1.1 on 2025-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistprofile",
            name="qualifications",
            field=models.TextField(blank=True),
        ),
    ]
