# Generated by Django 5.1.1 on 2025-01-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_user_role_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("therapist", "Therapist")],
                default="patient",
                max_length=10,
            ),
        ),
    ]
